export const items = [
  {
    id: 1,
    name: "iPhone 15 Pro Max",
    brand: "Apple",
    price: 1199.99,
    originalPrice: 1299.99,
    image: "/api/placeholder/300/300",
    rating: 4.8,
    reviews: 2543,
    discount: 8,
    inStock: true,
    isNew: true,
    colors: ["Natural Titanium", "Blue Titanium", "White Titanium"],
  },
  {
    id: 2,
    name: "Sony WH-1000XM5 Wireless Headphones",
    brand: "Sony",
    price: 349.99,
    originalPrice: 399.99,
    image: "/api/placeholder/300/300",
    rating: 4.9,
    reviews: 1876,
    discount: 12,
    inStock: true,
    isNew: false,
    colors: ["Black", "Silver"],
  },
  {
    id: 3,
    name: "MacBook Air M3",
    brand: "Apple",
    price: 1299.99,
    originalPrice: 1399.99,
    image: "/api/placeholder/300/300",
    rating: 4.7,
    reviews: 982,
    discount: 7,
    inStock: true,
    isNew: true,
    colors: ["Space Gray", "Silver", "Starlight"],
  },
  {
    id: 4,
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    price: 1099.99,
    originalPrice: 1199.99,
    image: "/api/placeholder/300/300",
    rating: 4.6,
    reviews: 1234,
    discount: 8,
    inStock: false,
    isNew: false,
    colors: ["Titanium Black", "Titanium Gray"],
  },
];
